#   Add your code here and add comments to your code 
#   to describe what each section of code is doing
import turtle as trtl
painter = trtl.Turtle()
painter.hideturtle()
color = str(input("what color do you want the rectangle outline to be?: "))
width = int(input("what do you want the width to be?: "))
height = int(input("what do you want the height to be?: "))
painter.pencolor(color)
painter.forward(width)
painter.left(90)
painter.forward(height)
painter.left(90)
painter.forward(width)
painter.left(90)
painter.forward(height)
incolor = str(input("what do you want the inside color to be?: "))
width = (width/5)
painter.pencolor(incolor)
painter.left(90)
painter.forward(width)
painter.left(90)
painter.forward(height)
painter.right(90)
painter.forward(width)
painter.right(90)
painter.forward(height)
painter.left(90)
painter.forward(width)
painter.left(90)
painter.forward(height)
painter.right(90)
painter.forward(width)
painter.right(90)
painter.forward(height)
painter.left(90)
painter.forward(width)
incolor2 = str(input("what do you want the second inside color to be?: "))
painter.pencolor(incolor2)
width = (width*5)
height = (height/5)
painter.left(90)
painter.forward(height)
painter.left(90)
painter.forward(width)
painter.right(90)
painter.forward(height)
painter.right(90)
painter.forward(width)
painter.left(90)
painter.forward(height)
painter.left(90)
painter.forward(width)
painter.right(90)
painter.forward(height)
painter.right(90)
painter.forward(width)
wn = trtl.Screen()
wn.mainloop()
